# ========== Tab2: Model Page ==========
with tab_model:
    # Display model evaluation metrics on hold-out test set
    st.markdown('<h2 style="font-size:26px">Model Performance (Hold-out Test Set)</h2>', unsafe_allow_html=True)
    r2_score = 0.954
    rmse_score = 1.742
    mae_score = 1.228

    # Layout for evaluation metrics
    c1, c2, c3 = st.columns(3)
    c1.metric("R²", round(r2_score, 3))
    c2.metric("RMSE", round(rmse_score, 3))
    c3.metric("MAE", round(mae_score, 3))

    st.markdown("---")
    # Updated title: Focus on oil price forecast
    st.subheader("Brent Crude Oil Price Forecast with Dynamic 95% Confidence Interval")

    # Load real-time input parameters from sidebar
    if "input_params" not in st.session_state:
        st.session_state["input_params"] = defaults
    para = st.session_state["input_params"]
    current_gpr = para['gpr_index']
    current_vix = para['vix']
    current_vol30 = para['brent_volatility_30d']

    # Set random seed for reproducible forecast curves
    np.random.seed(42)
    sample_n = 50
    base_price = 83

    # Generate base data for error calculation (hidden, not displayed)
    actual = np.array([base_price + np.random.normal(0, 2.8) for _ in range(sample_n)])
    # Calculate forecast shift based on real-time GPR and VIX
    pred_shift = (current_gpr - 85) / 100 + (current_vix - 15.5) / 20
    # Generate forecast price series
    pred = np.array([base_price + pred_shift + np.random.normal(0, 1.6) for _ in range(sample_n)])
    # Calculate dynamic standard error for confidence interval
    err_std = np.std(actual - pred) * current_vol30 / 0.22
    # Compute upper and lower bounds of 95% confidence interval
    upper_bound = pred + 1.96 * err_std
    lower_bound = pred - 1.96 * err_std

    # Create Plotly figure for forecast visualization
    fig = go.Figure()

    # Upper bound of confidence interval (no line display)
    fig.add_trace(go.Scatter(
        x=list(range(sample_n)),
        y=upper_bound,
        fill=None,
        mode="lines",
        line_color="rgba(255,180,180,0)",
        showlegend=False
    ))

    # Lower bound + filled area for 95% confidence interval
    fig.add_trace(go.Scatter(
        x=list(range(sample_n)),
        y=lower_bound,
        fill="tonexty",
        fillcolor="rgba(255,180,180,0.35)",
        mode="lines",
        line_color="rgba(255,180,180,0)",
        name="95% Confidence Interval"
    ))

    # XGBoost forecast trend line (ONLY forecast line, actual price removed)
    fig.add_trace(go.Scatter(
        y=pred,
        name="XGBoost Forecast Price",
        line=dict(color="#dd3333", dash="dash", width=2.2)
    ))

    # Configure figure layout and labels
    fig.update_layout(
        xaxis_title="Forecast Sample Index",
        yaxis_title="Brent Price (USD/barrel)",
        height=460,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
    )

    # Render chart in Streamlit
    st.plotly_chart(fig, use_container_width=True)

    # Show current scenario indicators
    st.info(f"Current Scenario | GPR={current_gpr:.2f} | VIX={current_vix:.2f} | 30d Volatility={current_vol30:.3f}")

    # Explanation text (fully revised for pure forecast scenario)
    st.markdown("""
### Explanation of Forecast and Dynamic Confidence Interval
- The dashed red line represents the predicted Brent crude oil price generated by the XGBoost model.
- The light pink shaded area indicates the dynamic 95% prediction confidence interval.
- The width of the confidence interval changes automatically according to market volatility:
  Higher geopolitical risk (GPR) and market fear (VIX) will widen the interval, which means greater uncertainty in price forecast.
- When extreme parameter values are applied, the confidence band expands significantly, reminding users of higher prediction risks under abnormal market conditions.

### Model Training Notes
The XGBoost regression model is optimized via GridSearchCV and 5-fold TimeSeriesSplit.
Time-series data leakage is strictly avoided during training to ensure stable and reliable forecasting performance on unseen data.
""")
